version: '3.4'

services:
  db:
     image: mysql:8.0.20
     environment:
       MYSQL_RANDOM_ROOT_PASSWORD: 1
       MYSQL_DATABASE: InternalWorkAuth
       MYSQL_USER: dbuser
       MYSQL_PASSWORD: dbuserpassword
     volumes:
       - dbdata:/var/lib/mysql
     restart: always

  internalwork.auth:
     depends_on:
       - db
     image: ${DOCKER_REGISTRY-}internalworkauth
     build:
       context: .
       dockerfile: InternalWork.Auth.WebAPI/Dockerfile
     environment:
       ASPNETCORE_ENVIRONMENT: docker

volumes:
  dbdata: